### ISSUE TITLE
Importing react throw error

### ISSUE THREAD

**Issue by eskimoblood** [jeffling/wallaby-webpack#12]
When I import react into module wallaby throws this error. I'm using the same config as the [Wallaby.js with React + Webpack + ES6example ](https://github.com/wallabyjs/wallaby-webpack-es6-react)

```
TypeError: 'undefined' is not a function (evaluating 'ReactElementValidator.createElement.bind(
      null,
      type
    )')
```

**Comment by ArtemGovorov** [comment]
The most likely reason is that Function.prototype.bind polyfill is not loaded. If you have the same config as in the repo that you've referenced, please double check that this module is installed and has this file:

```
`{pattern: 'node_modules/react-tools/src/test/phantomjs-shims.js', instrument: false},`
```

If you have some other file with `Function.prototype.bind` polyfill, you may just reference it instead of installing react-tools module, for example like is done in [this sample](https://github.com/wallabyjs/wallaby-react-todomvc-sample/blob/master/test/polyfill.js).

The reason you need to do this is because PhantomJs 1.x doesn't support `Function.prototype.bind`. PhantomJs 2 doesn't have this issue and [wallaby.js supports it](http://wallabyjs.com/docs/integration/phantomjs2.html), so you also consider using it and then you will not need the polyfill.

Please let me know if it fixes the issue for you.

**Comment by eskimoblood** [comment]
Installing react-tools fixed it. thanks
